// src/components/admin/project-form.tsx
'use client'

import { useEffect, useState } from 'react'
import { Field, FormSection, Input, Textarea } from './form-controls'

export type ProjectAdmin = {
  id?: number
  key: string
  titleEn: string
  titleRu: string
  titleKo: string
  descEn: string
  descRu: string
  descKo: string
  descriptionEn: string
  descriptionRu: string
  descriptionKo: string
  titleEs: string
  descEs: string
  descriptionEs: string
  order: number
  link: string
  githubLink: string
  deployLink: string
  image: string
  images: string[]
  stack: string[]
}

const EMPTY: ProjectAdmin = {
  key: '',
  titleEn: '',
  titleRu: '',
  titleKo: '',
  descEn: '',
  descRu: '',
  descKo: '',
  descriptionEn: '',
  descriptionRu: '',
  descriptionKo: '',
  titleEs: '',
  descEs: '',
  descriptionEs: '',
  order: 999,
  link: '',
  githubLink: '',
  deployLink: '',
  image: '',
  images: [],
  stack: [],
}

type Props = {
  project: ProjectAdmin | null
  adminSecret: string
  onSuccess: () => void
  onCancel: () => void
}

export function ProjectForm({ project, adminSecret, onSuccess, onCancel }: Props) {
  const [form, setForm] = useState<ProjectAdmin>(EMPTY)
  const [stackInput, setStackInput] = useState('')
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [uploading, setUploading] = useState(false)

  useEffect(() => {
    if (project) {
      setForm({ ...EMPTY, ...project, images: project.images ?? [], stack: project.stack ?? [] })
      setStackInput((project.stack ?? []).join(', '))
    } else {
      setForm(EMPTY)
      setStackInput('')
    }
    setError('')
  }, [project])

  function patch<K extends keyof ProjectAdmin>(k: K, v: ProjectAdmin[K]) {
    setForm((f) => ({ ...f, [k]: v }))
  }

  async function uploadFile(file: File): Promise<string> {
    const fd = new FormData()
    fd.append('file', file)
    const res = await fetch('/api/admin/upload', {
      method: 'POST',
      headers: { Authorization: `Bearer ${adminSecret}` },
      body: fd,
    })
    if (!res.ok) throw new Error('Upload failed')
    const data = await res.json()
    return data.url as string
  }

  async function handleMain(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    setUploading(true)
    setError('')
    try {
      const url = await uploadFile(file)
      patch('image', url)
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setUploading(false)
      e.target.value = ''
    }
  }

  async function handleGallery(e: React.ChangeEvent<HTMLInputElement>) {
    const files = Array.from(e.target.files || [])
    if (!files.length) return
    setUploading(true)
    setError('')
    try {
      const urls: string[] = []
      for (const f of files) urls.push(await uploadFile(f))
      setForm((f) => ({ ...f, images: [...f.images, ...urls] }))
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setUploading(false)
      e.target.value = ''
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const stack = stackInput.split(',').map((s) => s.trim()).filter(Boolean)
    const body = { ...form, stack }
    setSubmitting(true)
    setError('')
    try {
      const url = project?.id
        ? `/api/admin/projects/${project.id}`
        : '/api/admin/projects'
      const res = await fetch(url, {
        method: project?.id ? 'PATCH' : 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${adminSecret}`,
        },
        body: JSON.stringify(body),
      })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        throw new Error(data.error || 'Failed to save project')
      }
      onSuccess()
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <FormSection title="01 — Basics">
        <Field label="Key" required hint="unique slug, e.g. my-project">
          <Input
            value={form.key}
            onChange={(e) => patch('key', e.target.value)}
            placeholder="my-project"
            required
          />
        </Field>
        <div className="grid sm:grid-cols-2 gap-4">
          <Field label="GitHub link">
            <Input
              type="url"
              value={form.githubLink}
              onChange={(e) => patch('githubLink', e.target.value)}
              placeholder="https://github.com/..."
            />
          </Field>
          <Field label="Deploy link">
            <Input
              type="url"
              value={form.deployLink}
              onChange={(e) => patch('deployLink', e.target.value)}
              placeholder="https://..."
            />
          </Field>
        </div>
      </FormSection>

      {(['En', 'Ru', 'Ko', 'Es'] as const).map((suffix) => {
        const labels: Record<string, string> = {
          En: '02 — English',
          Ru: '03 — Russian',
          Ko: '04 — Korean',
          Es: '05 — Spanish',
        }
        const required = suffix === 'En' || suffix === 'Ru'
        return (
          <FormSection key={suffix} title={labels[suffix]}>
            <Field label="Title" required={required}>
              <Input
                value={(form as any)[`title${suffix}`] || ''}
                onChange={(e) => patch(`title${suffix}` as keyof ProjectAdmin, e.target.value as never)}
              />
            </Field>
            <Field label="Short description" hint="card preview">
              <Input
                value={(form as any)[`desc${suffix}`] || ''}
                onChange={(e) => patch(`desc${suffix}` as keyof ProjectAdmin, e.target.value as never)}
              />
            </Field>
            <Field label="Full description" hint="modal body, supports line breaks">
              <Textarea
                value={(form as any)[`description${suffix}`] || ''}
                onChange={(e) => patch(`description${suffix}` as keyof ProjectAdmin, e.target.value as never)}
              />
            </Field>
          </FormSection>
        )
      })}

      <FormSection title="06 — Images">
        <Field label="Main image (card thumbnail)">
          <input
            type="file"
            accept="image/*"
            disabled={uploading}
            onChange={handleMain}
            className="block w-full file:mr-3 file:py-2 file:px-4 file:brutal-border-2 file:bg-brutal-yellow file:font-mono file:text-xs file:font-bold file:uppercase file:cursor-pointer"
          />
          {form.image ? (
            <div className="mt-3 flex gap-3 items-start">
              <img src={form.image} className="w-32 h-24 object-cover brutal-border-2" alt="" />
              <button
                type="button"
                onClick={() => patch('image', '')}
                className="brutal-border-2 bg-brutal-red text-cream px-3 py-1 font-mono text-xs font-bold uppercase"
              >
                Remove
              </button>
            </div>
          ) : null}
          <details className="mt-3">
            <summary className="font-mono text-xs uppercase cursor-pointer">Paste URL manually</summary>
            <Input
              className="mt-2"
              value={form.image}
              onChange={(e) => patch('image', e.target.value)}
              placeholder="https://…"
            />
          </details>
        </Field>

        <Field label={`Gallery (${form.images.length})`}>
          <input
            type="file"
            accept="image/*"
            multiple
            disabled={uploading}
            onChange={handleGallery}
            className="block w-full file:mr-3 file:py-2 file:px-4 file:brutal-border-2 file:bg-brutal-pink file:text-cream file:font-mono file:text-xs file:font-bold file:uppercase file:cursor-pointer"
          />
          {form.images.length > 0 ? (
            <div className="mt-3 grid grid-cols-3 sm:grid-cols-4 gap-3">
              {form.images.map((url, idx) => (
                <div key={idx} className="relative">
                  <img src={url} alt="" className="w-full aspect-square object-cover brutal-border-2" />
                  <button
                    type="button"
                    onClick={() => patch('images', form.images.filter((_, i) => i !== idx))}
                    className="absolute -top-2 -right-2 grid place-items-center w-6 h-6 brutal-border-2 bg-brutal-red text-cream font-mono text-xs font-bold"
                  >
                    ×
                  </button>
                </div>
              ))}
            </div>
          ) : null}
        </Field>
      </FormSection>

      <FormSection title="07 — Tech stack">
        <Field label="Technologies" hint="comma separated">
          <Input
            value={stackInput}
            onChange={(e) => setStackInput(e.target.value)}
            placeholder="Vue, Nuxt, Tailwind, TypeScript"
          />
          <div className="mt-3 flex flex-wrap gap-2">
            {stackInput
              .split(',')
              .map((s) => s.trim())
              .filter(Boolean)
              .map((tag) => (
                <span key={tag} className="brutal-tag">
                  {tag}
                </span>
              ))}
          </div>
        </Field>
      </FormSection>

      {error ? (
        <p className="brutal-border-2 bg-brutal-red text-cream px-3 py-2 font-mono text-xs font-bold uppercase">
          {error}
        </p>
      ) : null}

      <div className="flex flex-col sm:flex-row gap-3 pt-4">
        <button
          type="button"
          onClick={onCancel}
          className="font-display uppercase text-sm tracking-tight px-5 py-3 bg-cream text-ink brutal-border brutal-press flex-1"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={submitting || uploading}
          className="font-display uppercase text-sm tracking-tight px-5 py-3 bg-ink text-cream brutal-border brutal-shadow brutal-press flex-1 disabled:opacity-50"
        >
          {submitting ? 'Saving…' : project?.id ? 'Update' : 'Create'}
        </button>
      </div>
    </form>
  )
}

// components/project-form.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-6 max-h-[70vh] overflow-y-auto pr-4">
    <div class="card bg-base-200 p-4">
      <h4 class="font-bold text-lg mb-4 flex items-center gap-2">
        <span class="badge badge-primary">1</span> Basic Information
      </h4>
      <div class="space-y-4">
        <div class="form-control">
          <label class="label">
            <span class="label-text font-semibold">Key</span>
            <span class="label-text-alt text-xs">Unique identifier (e.g., my-project)</span>
          </label>
          <input 
            v-model="form.key" 
            type="text" 
            required 
            class="input input-bordered focus:input-primary" 
            placeholder="my-project" 
          />
        </div>

        <div class="form-control">
          <label class="label">
            <span class="label-text font-semibold">GitHub Link</span>
            <span class="label-text-alt text-xs">Repository URL</span>
          </label>
          <input 
            v-model="form.githubLink" 
            type="url" 
            class="input input-bordered focus:input-primary" 
            placeholder="https://github.com/username/project" 
          />
        </div>

        <div class="form-control">
          <label class="label">
            <span class="label-text font-semibold">Deploy/Demo Link</span>
            <span class="label-text-alt text-xs">Live site URL</span>
          </label>
          <input 
            v-model="form.deployLink" 
            type="url" 
            class="input input-bordered focus:input-primary" 
            placeholder="https://my-project.vercel.app" 
          />
        </div>
      </div>
    </div>

    <div class="card bg-base-200 p-4">
      <h4 class="font-bold text-lg mb-4 flex items-center gap-2">
        <span class="badge badge-primary">2</span> English Content
      </h4>
      <div class="space-y-4">
        <div class="form-control">
          <label class="label">
            <span class="label-text font-semibold">Title</span>
            <span class="label-text-alt text-error">*</span>
          </label>
          <input 
            v-model="form.titleEn" 
            type="text" 
            required 
            class="input input-bordered focus:input-primary" 
            placeholder="My Awesome Project"
          />
        </div>
        
        <div class="form-control">
          <label class="label">
            <span class="label-text font-semibold">Short Description</span>
            <span class="label-text-alt text-xs">Card preview text</span>
          </label>
          <input 
            v-model="form.descEn" 
            type="text" 
            class="input input-bordered focus:input-primary" 
            placeholder="A brief one-line description"
          />
        </div>
        
        <div class="form-control">
          <label class="label">
            <span class="label-text font-semibold">Full Description</span>
            <span class="label-text-alt text-xs">Modal description (supports line breaks)</span>
          </label>
          <textarea 
            v-model="form.descriptionEn" 
            class="textarea textarea-bordered focus:textarea-primary h-40" 
            placeholder="Full project description with details, features, etc."
          ></textarea>
        </div>
      </div>
    </div>

    <div class="card bg-base-200 p-4">
      <h4 class="font-bold text-lg mb-4 flex items-center gap-2">
        <span class="badge badge-primary">3</span> Russian Content
      </h4>
      <div class="space-y-4">
        <div class="form-control">
          <label class="label">
            <span class="label-text font-semibold">Название</span>
            <span class="label-text-alt text-error">*</span>
          </label>
          <input 
            v-model="form.titleRu" 
            type="text" 
            required 
            class="input input-bordered focus:input-primary" 
            placeholder="Мой Прекрасный Проект"
          />
        </div>
        
        <div class="form-control">
          <label class="label">
            <span class="label-text font-semibold">Краткое описание</span>
            <span class="label-text-alt text-xs">Текст превью карточки</span>
          </label>
          <input 
            v-model="form.descRu" 
            type="text" 
            class="input input-bordered focus:input-primary" 
            placeholder="Краткое описание в одну строку"
          />
        </div>
        
        <div class="form-control">
          <label class="label">
            <span class="label-text font-semibold">Полное описание</span>
            <span class="label-text-alt text-xs">Описание в модальном окне</span>
          </label>
          <textarea 
            v-model="form.descriptionRu" 
            class="textarea textarea-bordered focus:textarea-primary h-40" 
            placeholder="Полное описание проекта с деталями, функциями и т.д."
          ></textarea>
        </div>
      </div>
    </div>

    <div class="card bg-base-200 p-4">
      <h4 class="font-bold text-lg mb-4 flex items-center gap-2">
        <span class="badge badge-primary">4</span> Images
      </h4>
      <div class="space-y-6">
        <div>
          <label class="label">
            <span class="label-text font-semibold">Main Image</span>
            <span class="label-text-alt text-xs">Card thumbnail</span>
          </label>
          <input 
            type="file" 
            @change="uploadMainImage" 
            accept="image/*" 
            class="file-input file-input-bordered file-input-primary w-full"
            :disabled="uploading"
          />
          <div v-if="uploading" class="mt-3">
            <progress class="progress progress-primary w-full"></progress>
            <p class="text-sm text-center mt-1 opacity-70">Uploading...</p>
          </div>
          <div v-if="form.image" class="mt-4 relative inline-block">
            <img :src="form.image" class="h-40 rounded-lg shadow-lg object-cover" />
            <button 
              type="button"
              @click="form.image = ''"
              class="btn btn-circle btn-xs btn-error absolute -top-2 -right-2 shadow-lg">
              ✕
            </button>
          </div>
          <div class="collapse collapse-arrow bg-base-300 mt-3">
            <input type="checkbox" /> 
            <div class="collapse-title text-sm font-medium">Advanced: Paste URL manually</div>
            <div class="collapse-content">
              <input 
                v-model="form.image" 
                type="text" 
                class="input input-bordered w-full input-sm mt-2" 
                placeholder="https://example.com/image.jpg" 
              />
            </div>
          </div>
        </div>

        <div class="divider"></div>
        <div>
          <label class="label">
            <span class="label-text font-semibold">Gallery Images</span>
            <span class="label-text-alt">
              <span class="badge badge-sm">{{ form.images.length }}</span> images
            </span>
          </label>
          <input 
            type="file" 
            @change="uploadGalleryImages" 
            accept="image/*" 
            multiple 
            class="file-input file-input-bordered file-input-secondary w-full"
            :disabled="uploading"
          />
          <div v-if="uploading" class="mt-3">
            <progress class="progress progress-secondary w-full"></progress>
            <p class="text-sm text-center mt-1 opacity-70">Uploading images...</p>
          </div>
          <div v-if="form.images.length" class="grid grid-cols-3 sm:grid-cols-4 gap-3 mt-4">
            <div 
              v-for="(img, i) in form.images" 
              :key="i" 
              class="relative group aspect-square rounded-lg overflow-hidden shadow-md hover:shadow-xl transition"
            >
              <img :src="img" class="w-full h-full object-cover" />
              <div class="absolute inset-0 bg-black/0 group-hover:bg-black/40 transition"></div>
              <button 
                type="button"
                @click="removeGalleryImage(i)"
                class="btn btn-circle btn-xs btn-error absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition shadow-lg">
                ✕
              </button>
            </div>
          </div>
          <div class="collapse collapse-arrow bg-base-300 mt-3">
            <input type="checkbox" /> 
            <div class="collapse-title text-sm font-medium">Advanced: Paste URLs manually (one per line)</div>
            <div class="collapse-content">
              <textarea 
                v-model="imagesText" 
                class="textarea textarea-bordered w-full h-24 text-sm mt-2"
                placeholder="https://example.com/image1.jpg&#10;https://example.com/image2.jpg"
              ></textarea>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Tech Stack -->
    <div class="card bg-base-200 p-4">
      <h4 class="font-bold text-lg mb-4 flex items-center gap-2">
        <span class="badge badge-primary">5</span> Tech Stack
      </h4>
      <div class="form-control">
        <label class="label">
          <span class="label-text font-semibold">Technologies</span>
          <span class="label-text-alt text-xs">Comma separated (press Tab or click out to update)</span>
        </label>
        <input 
          v-model="stackInput" 
          type="text" 
          class="input input-bordered focus:input-primary"
          placeholder="Vue, Nuxt, Tailwind CSS, TypeScript"
          @blur="updateStack"
        />
        <div v-if="form.stack.length" class="flex flex-wrap gap-2 mt-3">
          <span 
            v-for="(tech, i) in form.stack" 
            :key="tech" 
            class="badge badge-outline badge-lg gap-2"
          >
            {{ tech }}
            <button 
              type="button"
              @click="removeStack(i)"
              class="text-error hover:scale-125 transition">
              ✕
            </button>
          </span>
        </div>
      </div>
    </div>

    <div v-if="errorMessage" class="alert alert-error">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span>{{ errorMessage }}</span>
    </div>

    <div class="flex gap-3 pt-4 border-t sticky bottom-0 bg-base-100 pb-4">
      <button type="button" @click="$emit('cancel')" class="btn btn-ghost flex-1">
        Cancel
      </button>
      <button type="submit" class="btn btn-primary flex-1" :disabled="submitting || uploading">
        <span v-if="submitting" class="loading loading-spinner"></span>
        <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path d="M7.707 10.293a1 1 0 10-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 11.586V6h5a2 2 0 012 2v7a2 2 0 01-2 2H4a2 2 0 01-2-2V8a2 2 0 012-2h5v5.586l-1.293-1.293zM9 4a1 1 0 012 0v2H9V4z" />
        </svg>
        {{ submitting ? 'Saving...' : (project ? 'Update Project' : 'Create Project') }}
      </button>
    </div>
  </form>
</template>

<script setup lang="ts">
const props = defineProps<{
  project?: any
  adminSecret: string
}>()

const emit = defineEmits<{
  success: []
  cancel: []
}>()

const submitting = ref(false)
const uploading = ref(false)
const errorMessage = ref('')
const stackInput = ref('')
const imagesInput = ref('')

const form = reactive({
  key: '',
  titleEn: '',
  titleRu: '',
  descEn: '',
  descRu: '',
  descriptionEn: '',
  descriptionRu: '',
  link: '',
  githubLink: '',
  deployLink: '',
  image: '',
  images: [] as string[],
  stack: [] as string[]
})

watch(() => props.project, (newProject) => {
  if (newProject) {
    form.key = newProject.key || ''
    form.titleEn = newProject.titleEn || ''
    form.titleRu = newProject.titleRu || ''
    form.descEn = newProject.descEn || ''
    form.descRu = newProject.descRu || ''
    form.descriptionEn = newProject.descriptionEn || ''
    form.descriptionRu = newProject.descriptionRu || ''
    form.link = newProject.link || ''
    form.githubLink = newProject.githubLink || ''
    form.deployLink = newProject.deployLink || ''
    form.image = newProject.image || ''
    form.images = newProject.images ? [...newProject.images] : []
    form.stack = newProject.stack ? [...newProject.stack] : []
    stackInput.value = newProject.stack ? newProject.stack.join(', ') : ''
    imagesInput.value = newProject.images ? newProject.images.join('\n') : ''
  } else {
    form.key = ''
    form.titleEn = ''
    form.titleRu = ''
    form.descEn = ''
    form.descRu = ''
    form.descriptionEn = ''
    form.descriptionRu = ''
    form.link = ''
    form.githubLink = ''
    form.deployLink = ''
    form.image = ''
    form.images = []
    form.stack = []
    stackInput.value = ''
    imagesInput.value = ''
  }
  errorMessage.value = ''
}, { immediate: true })

const imagesText = computed({
  get: () => imagesInput.value,
  set: (value) => {
    imagesInput.value = value
    form.images = value.split('\n').map(s => s.trim()).filter(Boolean)
  }
})

const updateStack = () => {
  form.stack = stackInput.value
    .split(',')
    .map(s => s.trim())
    .filter(Boolean)
}

const removeStack = (index: number) => {
  form.stack.splice(index, 1)
  stackInput.value = form.stack.join(', ')
}

const uploadMainImage = async (event: Event) => {
  const file = (event.target as HTMLInputElement).files?.[0]
  if (!file) return

  uploading.value = true
  try {
    const formData = new FormData()
    formData.append('file', file)

    const response = await $fetch('/api/admin/upload', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${props.adminSecret}`
      },
      body: formData
    })

    form.image = response.url
  } catch (err: any) {
    errorMessage.value = 'Upload failed: ' + err.message
  } finally {
    uploading.value = false
  }
}

const uploadGalleryImages = async (event: Event) => {
  const files = Array.from((event.target as HTMLInputElement).files || [])
  if (!files.length) return

  uploading.value = true
  try {
    for (const file of files) {
      const formData = new FormData()
      formData.append('file', file)

      const response = await $fetch('/api/admin/upload', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${props.adminSecret}`
        },
        body: formData
      })

      form.images.push(response.url)
    }
  } catch (err: any) {
    errorMessage.value = 'Upload failed: ' + err.message
  } finally {
    uploading.value = false
  }
}

const removeGalleryImage = (index: number) => {
  form.images.splice(index, 1)
}

const handleSubmit = async () => {
  submitting.value = true
  errorMessage.value = ''
  updateStack()

  try {
    if (props.project) {
      await $fetch(`/api/admin/projects/${props.project.id}`, {
        method: 'PATCH',
        headers: {
          'Authorization': `Bearer ${props.adminSecret}`
        },
        body: form
      })
    } else {
      await $fetch('/api/admin/projects', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${props.adminSecret}`
        },
        body: form
      })
    }

    emit('success')
  } catch (err: any) {
    errorMessage.value = err.data?.message || err.message || 'Failed to save project'
  } finally {
    submitting.value = false
  }
}
</script>
